services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: sh -c "npx prisma migrate deploy --schema apps/reservations/prisma/schema.prisma && npx prisma generate --schema apps/reservations/prisma/schema.prisma && npm run start:dev reservations"
    depends_on:
      - postgres
    env_file:
      - ./apps/reservations/.env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: sh -c "npx prisma migrate deploy --schema apps/auth/prisma/schema.prisma && npx prisma generate --schema apps/auth/prisma/schema.prisma && npm run start:dev auth"
    depends_on:
      - postgres
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    env_file:
      - ./apps/payments/.env
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: npm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      #POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      #POSTGRES_DB: postgres